"""
J.A.R.V.I.S — Dev Agent
Autonomous project builder. Give JARVIS a goal and it plans the architecture,
writes every file, installs dependencies, runs the project, and auto-fixes errors.

Usage:
    agent = DevAgent(jarvis)
    result = await agent.build_project("snake game in Python")
    # or synchronously:
    result = agent.build_project_sync("snake game in Python")
"""

import os
import re
import sys
import json
import time
import shutil
import logging
import subprocess
import threading
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Callable

from core.subprocess_utils import run_text

logger = logging.getLogger("jarvis.dev_agent")


# ═══════════════════════════════════════════════════════════
#  Data Models
# ═══════════════════════════════════════════════════════════

@dataclass
class FileSpec:
    """Specification for a single file in a project."""
    path: str                    # relative path (e.g., "src/main.py")
    description: str             # what this file does
    content: str = ""            # generated code content
    written: bool = False        # whether it's been written to disk


@dataclass
class ProjectPlan:
    """Full project plan generated by the LLM."""
    name: str                    # project name
    description: str             # what the project does
    language: str                # python, javascript, etc.
    files: list                  # list of FileSpec
    entry_point: str             # which file to run
    dependencies: list           # packages to install
    build_commands: list         # build steps if needed
    output_dir: str = ""         # where to create the project


@dataclass
class RunResult:
    """Result of running the project."""
    success: bool
    output: str = ""
    error_output: str = ""
    error_file: str = ""
    return_code: int = -1


@dataclass
class ProjectResult:
    """Final result of the entire build process."""
    success: bool
    project_dir: str
    files_created: list = field(default_factory=list)
    errors: list = field(default_factory=list)
    fix_attempts: int = 0
    summary: str = ""


# ═══════════════════════════════════════════════════════════
#  LLM Prompt Templates
# ═══════════════════════════════════════════════════════════

ARCHITECT_PROMPT = """You are a senior software architect. Plan a project for this goal:
"{goal}"

Language: {language}

Return ONLY valid JSON (no markdown, no code blocks, no explanation):
{{
  "name": "project-name",
  "description": "what it does",
  "files": [
    {{"path": "main.py", "description": "Entry point - handles X"}},
    {{"path": "utils.py", "description": "Utility functions for Y"}}
  ],
  "entry_point": "main.py",
  "dependencies": ["package1", "package2"],
  "build_commands": []
}}

Rules:
- Keep it simple — minimum files needed (max 10 files)
- Use standard libraries where possible to minimize dependencies
- Include a requirements.txt or package.json if there are external dependencies
- Entry point should be runnable with `python main.py` or `node index.js`
- Project name should be lowercase with hyphens, no spaces
- dependencies should only list pip/npm package names, not standard library modules
"""

FILE_WRITE_PROMPT = """Write the complete code for this file.

Project: {project_description}
File: {file_path} — {file_description}

Other files in the project:
{other_files}

Dependencies available: {dependencies}

Rules:
- Write COMPLETE, RUNNABLE code — no placeholders, no TODOs, no "implement this"
- Include ALL imports at the top
- Follow best practices for {language}
- Make sure the code actually works end to end
- Return ONLY the code — no markdown code blocks, no ``` markers, no explanation before or after
- The very first character of your response should be the first character of the code
"""

FIX_ERROR_PROMPT = """This project has an error when running. Fix it.

Project: {project_description}
Entry point: {entry_point}

Error output:
{error_output}

File that likely has the bug ({error_file}):
```
{file_content}
```

Other project files for context:
{other_files_content}

Fix the error. Return ONLY the corrected complete file content for {error_file}.
No markdown code blocks, no ``` markers, no explanation.
The very first character of your response should be the first character of the corrected code.
"""

EXPLAIN_PROMPT = """Analyze and explain this project. Be concise but thorough.

Project directory: {project_dir}

Files and their contents:
{files_content}

Explain:
1. What the project does (1-2 sentences)
2. Architecture — how the files relate
3. Key dependencies and why they're used
4. How to run it
5. Any potential issues or improvements
"""


# ═══════════════════════════════════════════════════════════
#  Dev Agent — Autonomous Project Builder
# ═══════════════════════════════════════════════════════════

class DevAgent:
    """
    JARVIS's autonomous developer agent.
    Give it a goal and it builds the entire project:
    plan → write → install → run → fix → deliver.
    """

    MAX_FIX_ATTEMPTS = 3
    MAX_FILES = 10
    RUN_TIMEOUT = 30  # seconds

    def __init__(self, jarvis):
        """
        Args:
            jarvis: The main JARVIS app instance, used for LLM access via jarvis.brain.
        """
        self.jarvis = jarvis
        self.brain = jarvis.brain
        self._lock = threading.Lock()

    # ─── Main Entry Point ─────────────────────────────────

    def build_project(
        self,
        goal: str,
        language: str = "python",
        output_dir: Optional[str] = None,
        progress_cb: Optional[Callable] = None,
    ) -> ProjectResult:
        """
        Build an entire project from a natural-language goal.

        Args:
            goal: What to build (e.g., "a snake game with score tracking").
            language: Target language (python, javascript, etc.).
            output_dir: Where to create the project. Defaults to ~/Desktop/jarvis_projects/.
            progress_cb: Optional callback — progress_cb(step, message).
                         Steps: planning, writing, installing, running, fixing, done.

        Returns:
            ProjectResult with success status, file list, errors, and summary.
        """
        errors = []
        files_created = []
        fix_attempts = 0

        def _progress(step: str, msg: str):
            logger.info(f"[DevAgent] {step}: {msg}")
            if progress_cb:
                try:
                    progress_cb(step, msg)
                except Exception:
                    pass

        try:
            # ── Step 1: Plan ──
            _progress("planning", f"Planning architecture for: {goal}")
            plan = self.plan_architecture(goal, language)

            if not plan or not plan.files:
                return ProjectResult(
                    success=False,
                    project_dir="",
                    errors=["Failed to generate a project plan."],
                    summary="Architecture planning failed — the LLM didn't return a valid plan.",
                )

            # Set output directory
            if output_dir:
                plan.output_dir = output_dir
            elif not plan.output_dir:
                desktop = Path.home() / "Desktop" / "jarvis_projects"
                plan.output_dir = str(desktop / plan.name)

            # Create output directory
            os.makedirs(plan.output_dir, exist_ok=True)
            _progress("planning", f"Project: {plan.name} — {len(plan.files)} files → {plan.output_dir}")

            # ── Step 2: Write Files ──
            _progress("writing", "Generating code for all files...")
            for i, fspec in enumerate(plan.files):
                _progress("writing", f"Writing {fspec.path}... ({i + 1}/{len(plan.files)})")
                code = self.write_file(fspec, plan)
                if code:
                    fspec.content = code
                    full_path = os.path.join(plan.output_dir, fspec.path)
                    self._save_file(full_path, code)
                    fspec.written = True
                    files_created.append(fspec.path)
                else:
                    errors.append(f"Failed to generate code for {fspec.path}")

            if not files_created:
                return ProjectResult(
                    success=False,
                    project_dir=plan.output_dir,
                    errors=errors,
                    summary="Code generation failed — no files were written.",
                )

            # ── Step 3: Install Dependencies ──
            if plan.dependencies:
                _progress("installing", f"Installing: {', '.join(plan.dependencies)}")
                install_ok = self.install_dependencies(plan)
                if not install_ok:
                    errors.append("Some dependencies failed to install (project may still work).")

            # ── Step 4: Run Build Commands ──
            if plan.build_commands:
                _progress("installing", "Running build commands...")
                for cmd in plan.build_commands:
                    try:
                        run_text(
                            cmd, shell=True, cwd=plan.output_dir,
                            timeout=60, capture_output=True,
                        )
                    except Exception as e:
                        errors.append(f"Build command '{cmd}' failed: {e}")

            # ── Step 5: Run & Auto-Fix Loop ──
            _progress("running", "Running the project...")
            run_result = self.run_project(plan)

            while not run_result.success and fix_attempts < self.MAX_FIX_ATTEMPTS:
                fix_attempts += 1
                _progress("fixing", f"Error detected — fix attempt {fix_attempts}/{self.MAX_FIX_ATTEMPTS}")
                errors.append(f"Run error (attempt {fix_attempts}): {run_result.error_output[:300]}")

                fixed = self.fix_errors(plan, run_result, fix_attempts)
                if not fixed:
                    _progress("fixing", "Could not generate a fix.")
                    break

                _progress("running", f"Retrying after fix #{fix_attempts}...")
                run_result = self.run_project(plan)

            # ── Step 6: Report ──
            success = run_result.success
            if success:
                summary = (
                    f"Project '{plan.name}' built successfully!\n"
                    f"  Location: {plan.output_dir}\n"
                    f"  Files: {len(files_created)}\n"
                    f"  Entry point: {plan.entry_point}\n"
                    f"  Fix attempts needed: {fix_attempts}"
                )
            else:
                summary = (
                    f"Project '{plan.name}' was created but has runtime errors.\n"
                    f"  Location: {plan.output_dir}\n"
                    f"  Files: {len(files_created)}\n"
                    f"  Fix attempts: {fix_attempts}/{self.MAX_FIX_ATTEMPTS}\n"
                    f"  Last error: {run_result.error_output[:200]}"
                )

            _progress("done", summary)
            return ProjectResult(
                success=success,
                project_dir=plan.output_dir,
                files_created=files_created,
                errors=errors,
                fix_attempts=fix_attempts,
                summary=summary,
            )

        except Exception as e:
            logger.exception("[DevAgent] build_project failed")
            return ProjectResult(
                success=False,
                project_dir=output_dir or "",
                files_created=files_created,
                errors=errors + [f"Unexpected error: {e}"],
                fix_attempts=fix_attempts,
                summary=f"Build failed with unexpected error: {e}",
            )

    # ─── Architecture Planning ────────────────────────────

    def plan_architecture(self, goal: str, language: str) -> Optional[ProjectPlan]:
        """
        Ask the LLM to design a project architecture.

        Returns:
            ProjectPlan or None if planning fails.
        """
        prompt = ARCHITECT_PROMPT.format(goal=goal, language=language)

        raw = self._llm_generate(prompt)
        if not raw:
            logger.error("[DevAgent] LLM returned empty response for architecture")
            return None

        # Parse JSON from the response
        data = self._extract_json(raw)
        if not data:
            logger.error("[DevAgent] Could not parse architecture JSON from LLM response")
            return None

        try:
            files = []
            for f in data.get("files", [])[:self.MAX_FILES]:
                files.append(FileSpec(
                    path=f.get("path", ""),
                    description=f.get("description", ""),
                ))

            if not files:
                logger.error("[DevAgent] No files in architecture plan")
                return None

            plan = ProjectPlan(
                name=data.get("name", "jarvis-project"),
                description=data.get("description", goal),
                language=language,
                files=files,
                entry_point=data.get("entry_point", files[0].path),
                dependencies=data.get("dependencies", []),
                build_commands=data.get("build_commands", []),
            )
            return plan

        except Exception as e:
            logger.error(f"[DevAgent] Failed to parse project plan: {e}")
            return None

    # ─── File Writing ─────────────────────────────────────

    def write_file(self, fspec: FileSpec, plan: ProjectPlan) -> Optional[str]:
        """
        Ask the LLM to write the complete code for one file.

        Args:
            fspec: The FileSpec to generate code for.
            plan: The full project plan (for context).

        Returns:
            Generated code as a string, or None on failure.
        """
        # Build context of other files
        other_files = "\n".join(
            f"  - {f.path}: {f.description}"
            for f in plan.files if f.path != fspec.path
        )
        if not other_files:
            other_files = "(this is the only file)"

        deps = ", ".join(plan.dependencies) if plan.dependencies else "(standard library only)"

        prompt = FILE_WRITE_PROMPT.format(
            project_description=plan.description,
            file_path=fspec.path,
            file_description=fspec.description,
            other_files=other_files,
            dependencies=deps,
            language=plan.language,
        )

        raw = self._llm_generate(prompt)
        if not raw:
            return None

        # Strip markdown code fences if the LLM included them
        code = self._strip_code_fences(raw)
        return code

    # ─── Dependency Installation ──────────────────────────

    def install_dependencies(self, plan: ProjectPlan) -> bool:
        """
        Install project dependencies.

        Returns:
            True if all dependencies installed successfully.
        """
        if not plan.dependencies:
            return True

        lang = plan.language.lower()
        all_ok = True

        if lang in ("python", "py"):
            all_ok = self._pip_install(plan.dependencies, plan.output_dir)
        elif lang in ("javascript", "js", "node", "nodejs", "typescript", "ts"):
            all_ok = self._npm_install(plan.dependencies, plan.output_dir)
        else:
            logger.warning(f"[DevAgent] No installer configured for language: {lang}")
            return True  # Don't block — might work without

        return all_ok

    def _pip_install(self, packages: list, cwd: str) -> bool:
        """Install Python packages via pip."""
        # Try bulk install first
        try:
            result = run_text(
                [sys.executable, "-m", "pip", "install"] + packages,
                capture_output=True, timeout=120, cwd=cwd,
            )
            if result.returncode == 0:
                logger.info(f"[DevAgent] pip installed: {', '.join(packages)}")
                return True
        except Exception as e:
            logger.warning(f"[DevAgent] Bulk pip install failed: {e}")

        # Fallback: install one by one
        all_ok = True
        for pkg in packages:
            try:
                result = run_text(
                    [sys.executable, "-m", "pip", "install", pkg],
                    capture_output=True, timeout=60, cwd=cwd,
                )
                if result.returncode != 0:
                    logger.warning(f"[DevAgent] pip install {pkg} failed: {result.stderr[:200]}")
                    all_ok = False
                else:
                    logger.info(f"[DevAgent] pip installed: {pkg}")
            except Exception as e:
                logger.warning(f"[DevAgent] pip install {pkg} error: {e}")
                all_ok = False

        return all_ok

    def _npm_install(self, packages: list, cwd: str) -> bool:
        """Install Node.js packages via npm."""
        # Ensure package.json exists
        pkg_json = os.path.join(cwd, "package.json")
        if not os.path.exists(pkg_json):
            init_data = {"name": "jarvis-project", "version": "1.0.0", "private": True}
            with open(pkg_json, "w") as f:
                json.dump(init_data, f, indent=2)

        try:
            result = run_text(
                ["npm", "install"] + packages,
                capture_output=True, timeout=120,
                cwd=cwd, shell=True,
            )
            if result.returncode == 0:
                logger.info(f"[DevAgent] npm installed: {', '.join(packages)}")
                return True
            else:
                logger.warning(f"[DevAgent] npm install failed: {result.stderr[:200]}")
                return False
        except Exception as e:
            logger.warning(f"[DevAgent] npm install error: {e}")
            return False

    # ─── Run Project ──────────────────────────────────────

    def run_project(self, plan: ProjectPlan) -> RunResult:
        """
        Run the project's entry point and capture output.

        Returns:
            RunResult with success status and output/errors.
        """
        entry = os.path.join(plan.output_dir, plan.entry_point)
        if not os.path.exists(entry):
            return RunResult(
                success=False,
                error_output=f"Entry point not found: {entry}",
                error_file=plan.entry_point,
            )

        lang = plan.language.lower()
        if lang in ("python", "py"):
            cmd = [sys.executable, entry]
        elif lang in ("javascript", "js", "node", "nodejs"):
            cmd = ["node", entry]
        elif lang in ("typescript", "ts"):
            cmd = ["npx", "ts-node", entry]
        else:
            cmd = [sys.executable, entry]  # default to python

        try:
            result = run_text(
                cmd,
                capture_output=True,
                timeout=self.RUN_TIMEOUT,
                cwd=plan.output_dir,
            )

            if result.returncode == 0:
                return RunResult(
                    success=True,
                    output=result.stdout,
                    return_code=0,
                )
            else:
                # Try to identify which file has the error
                error_file = self._identify_error_file(result.stderr, plan)
                return RunResult(
                    success=False,
                    output=result.stdout,
                    error_output=result.stderr,
                    error_file=error_file,
                    return_code=result.returncode,
                )

        except subprocess.TimeoutExpired:
            # Timeout might be okay for GUI apps / servers — treat as success
            return RunResult(
                success=True,
                output="(process ran for 30s without crashing — likely a GUI or server app)",
                return_code=0,
            )
        except Exception as e:
            return RunResult(
                success=False,
                error_output=str(e),
                error_file=plan.entry_point,
            )

    # ─── Error Fixing ─────────────────────────────────────

    def fix_errors(self, plan: ProjectPlan, run_result: RunResult, attempt: int) -> bool:
        """
        Send the error to the LLM and apply the fix.

        Returns:
            True if a fix was generated and applied.
        """
        error_file = run_result.error_file or plan.entry_point

        # Read the current content of the broken file
        full_path = os.path.join(plan.output_dir, error_file)
        try:
            with open(full_path, "r", encoding="utf-8") as f:
                file_content = f.read()
        except Exception:
            file_content = "(could not read file)"

        # Build context of other files
        other_files_content = ""
        for fspec in plan.files:
            if fspec.path == error_file:
                continue
            other_path = os.path.join(plan.output_dir, fspec.path)
            try:
                with open(other_path, "r", encoding="utf-8") as f:
                    content = f.read()
                other_files_content += f"\n--- {fspec.path} ---\n{content}\n"
            except Exception:
                pass

        if not other_files_content:
            other_files_content = "(no other files)"

        prompt = FIX_ERROR_PROMPT.format(
            project_description=plan.description,
            entry_point=plan.entry_point,
            error_output=run_result.error_output[:1500],
            error_file=error_file,
            file_content=file_content,
            other_files_content=other_files_content[:3000],
        )

        raw = self._llm_generate(prompt)
        if not raw:
            return False

        fixed_code = self._strip_code_fences(raw)
        if not fixed_code or fixed_code.strip() == file_content.strip():
            return False

        # Write the fix
        self._save_file(full_path, fixed_code)
        logger.info(f"[DevAgent] Applied fix to {error_file} (attempt {attempt})")

        # Update the FileSpec content
        for fspec in plan.files:
            if fspec.path == error_file:
                fspec.content = fixed_code
                break

        return True

    # ─── Explain Existing Project ─────────────────────────

    def explain_project(self, project_dir: str) -> str:
        """
        Analyze and explain an existing project's code.

        Args:
            project_dir: Path to the project directory.

        Returns:
            Human-readable explanation of the project.
        """
        if not os.path.isdir(project_dir):
            return f"Directory not found: {project_dir}"

        # Gather files (common code extensions)
        code_extensions = {
            ".py", ".js", ".ts", ".jsx", ".tsx", ".java", ".c", ".cpp",
            ".h", ".go", ".rs", ".rb", ".php", ".html", ".css", ".json",
            ".yaml", ".yml", ".toml", ".cfg", ".ini", ".sh", ".bat",
        }

        files_content = ""
        file_count = 0
        for root, dirs, files in os.walk(project_dir):
            # Skip hidden dirs, node_modules, __pycache__, .git
            dirs[:] = [
                d for d in dirs
                if not d.startswith(".") and d not in ("node_modules", "__pycache__", "venv", ".venv")
            ]
            for fname in sorted(files):
                ext = os.path.splitext(fname)[1].lower()
                if ext in code_extensions:
                    fpath = os.path.join(root, fname)
                    rel = os.path.relpath(fpath, project_dir)
                    try:
                        with open(fpath, "r", encoding="utf-8", errors="replace") as f:
                            content = f.read(10000)  # cap per file
                        files_content += f"\n=== {rel} ===\n{content}\n"
                        file_count += 1
                        if file_count >= 15:
                            files_content += "\n(... more files truncated ...)\n"
                            break
                    except Exception:
                        pass
            if file_count >= 15:
                break

        if not files_content:
            return "No code files found in that directory."

        prompt = EXPLAIN_PROMPT.format(
            project_dir=project_dir,
            files_content=files_content[:8000],
        )

        explanation = self._llm_generate(prompt)
        return explanation or "Couldn't generate an explanation — LLM didn't respond."

    # ═══════════════════════════════════════════════════════
    #  Internal Helpers
    # ═══════════════════════════════════════════════════════

    def _llm_generate(self, prompt: str) -> Optional[str]:
        """
        Send a prompt to the LLM via JARVIS's brain and return the response.
        Thread-safe. Uses a dedicated message list (no pollution of chat history).
        """
        with self._lock:
            try:
                messages = [{"role": "user", "content": prompt}]
                system = (
                    "You are a senior software developer working as part of the JARVIS AI system. "
                    "You write clean, complete, production-quality code. "
                    "Follow instructions precisely. Return exactly what is asked — "
                    "no extra commentary unless requested."
                )
                reply, _latency = self.brain._chat_with_fallback(
                    messages=messages,
                    system_prompt=system,
                    max_tokens=self.brain.config.get("max_tokens", 4096),
                )
                return reply.strip() if reply else None
            except Exception as e:
                logger.error(f"[DevAgent] LLM call failed: {e}")
                return None

    def _extract_json(self, text: str) -> Optional[dict]:
        """
        Extract a JSON object from LLM output, handling markdown fences
        and other formatting noise.
        """
        if not text:
            return None

        # Strip markdown code fences
        text = text.strip()
        text = re.sub(r"^```(?:json)?\s*\n?", "", text)
        text = re.sub(r"\n?```\s*$", "", text)
        text = text.strip()

        # Try direct parse
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            pass

        # Try to find JSON object in the text
        match = re.search(r"\{[\s\S]*\}", text)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                pass

        # Last resort: find the outermost braces
        brace_start = text.find("{")
        brace_end = text.rfind("}")
        if brace_start != -1 and brace_end > brace_start:
            try:
                return json.loads(text[brace_start:brace_end + 1])
            except json.JSONDecodeError:
                pass

        return None

    def _strip_code_fences(self, text: str) -> str:
        """Remove markdown code fences from LLM output."""
        if not text:
            return ""

        text = text.strip()

        # Remove opening fence: ```python, ```js, ```
        text = re.sub(r"^```[a-zA-Z]*\s*\n?", "", text)
        # Remove closing fence
        text = re.sub(r"\n?```\s*$", "", text)

        return text.strip()

    def _save_file(self, filepath: str, content: str):
        """Write content to a file, creating parent directories as needed."""
        os.makedirs(os.path.dirname(filepath), exist_ok=True) if os.path.dirname(filepath) else None
        with open(filepath, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        logger.info(f"[DevAgent] Saved: {filepath}")

    def _identify_error_file(self, stderr: str, plan: ProjectPlan) -> str:
        """
        Try to identify which file caused the error from the traceback.
        Falls back to the entry point.
        """
        if not stderr:
            return plan.entry_point

        # Look for file references in Python tracebacks
        # Pattern: File "path/to/file.py", line N
        matches = re.findall(r'File "([^"]+)"', stderr)
        for match in reversed(matches):  # last file in traceback is usually the culprit
            basename = os.path.basename(match)
            for fspec in plan.files:
                if os.path.basename(fspec.path) == basename or fspec.path.endswith(basename):
                    return fspec.path

        # Look for Node.js style errors: at Object.<anonymous> (path:line:col)
        matches = re.findall(r"\(([^)]+):\d+:\d+\)", stderr)
        for match in reversed(matches):
            basename = os.path.basename(match)
            for fspec in plan.files:
                if os.path.basename(fspec.path) == basename:
                    return fspec.path

        return plan.entry_point
