"""
J.A.R.V.I.S — ConversationMemoryPlugin
Persistent conversation storage across JARVIS sessions for learning and recall.

Auto-generated by JARVIS Self-Modification Engine. Fixed to follow PluginBase contract.
"""

import json
import os
from datetime import datetime

from core.plugin_manager import PluginBase


class ConversationMemoryPlugin(PluginBase):
    """
    Stores and retrieves conversation history across sessions.

    Commands:
        /recall: Search or recall past conversations
        /memory_stats: Show conversation memory statistics
        /clear_memory: Clear stored conversations
    """

    name = "conversation_memory"
    description = "Persistent conversation storage across sessions"

    def activate(self):
        self._memory_file = os.path.join(
            os.path.expanduser("~"), ".jarvis_conversations.json"
        )
        self.conversations = self._load()
        print(f"Conversation Memory Plugin loaded. {len(self.conversations)} conversations.")

    def deactivate(self):
        self._save()

    def on_command(self, command: str, args: str) -> bool:
        if command == "/recall":
            self._recall(args)
            return True
        if command == "/memory_stats":
            self._stats()
            return True
        if command == "/clear_memory":
            self.conversations.clear()
            self._save()
            self.jarvis.chat.add_message("assistant", "Conversation memory cleared.")
            return True
        return False

    def on_message(self, message: str) -> str | None:
        return None

    def on_response(self, response: str):
        """Auto-save every exchange."""
        try:
            user_msg = ""
            if hasattr(self.jarvis, "brain") and self.jarvis.brain.history:
                for m in reversed(self.jarvis.brain.history):
                    if m.get("role") == "user":
                        user_msg = m.get("content", "")
                        break

            if user_msg and response:
                self.conversations.append({
                    "timestamp": datetime.now().isoformat(),
                    "user": user_msg[:500],
                    "assistant": response[:500],
                })
                # Keep last 200 exchanges
                if len(self.conversations) > 200:
                    self.conversations = self.conversations[-200:]
                self._save()
        except Exception:
            pass

    # ── Internal ──────────────────────────────────────────────

    def _load(self) -> list:
        try:
            if os.path.exists(self._memory_file):
                with open(self._memory_file, "r", encoding="utf-8") as f:
                    return json.load(f)
        except Exception:
            pass
        return []

    def _save(self):
        try:
            with open(self._memory_file, "w", encoding="utf-8") as f:
                json.dump(self.conversations, f, indent=2, ensure_ascii=False)
        except Exception:
            pass

    def _recall(self, query: str):
        if not self.conversations:
            self.jarvis.chat.add_message("assistant", "No stored conversations yet.")
            return

        if not query.strip():
            # Show last 3 conversations
            recent = self.conversations[-3:]
            lines = ["Recent conversations:"]
            for c in recent:
                ts = c["timestamp"][:16].replace("T", " ")
                lines.append(f"  [{ts}] You: {c['user'][:60]}...")
                lines.append(f"           Me: {c['assistant'][:60]}...")
            self.jarvis.chat.add_message("assistant", "\n".join(lines))
            return

        # Search
        query_lower = query.lower()
        matches = [
            c for c in self.conversations
            if query_lower in c.get("user", "").lower()
            or query_lower in c.get("assistant", "").lower()
        ]

        if not matches:
            self.jarvis.chat.add_message(
                "assistant", f"No conversations found matching '{query}'."
            )
            return

        lines = [f"Found {len(matches)} matching conversation(s):"]
        for c in matches[-5:]:
            ts = c["timestamp"][:16].replace("T", " ")
            lines.append(f"  [{ts}] You: {c['user'][:60]}")
            lines.append(f"           Me: {c['assistant'][:60]}")
        self.jarvis.chat.add_message("assistant", "\n".join(lines))

    def _stats(self):
        total = len(self.conversations)
        if not total:
            self.jarvis.chat.add_message("assistant", "No conversations stored yet.")
            return

        oldest = self.conversations[0]["timestamp"][:10]
        newest = self.conversations[-1]["timestamp"][:10]
        self.jarvis.chat.add_message(
            "assistant",
            f"Conversation memory: {total} exchanges stored\n"
            f"Oldest: {oldest} · Newest: {newest}",
        )
