import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import {
  RiFolderOpenLine,
  RiGalleryLine,
  RiImage2Line
} from 'react-icons/ri'
import type { JarvisShellSnapshot } from '../lib/types'

/* ═══════════════════════════════════════════
   Gallery View — IRIS-style image grid
   ═══════════════════════════════════════════ */

export default function GalleryView({ images }: { images: JarvisShellSnapshot['gallery'] }) {
  const [selected, setSelected] = useState<JarvisShellSnapshot['gallery'][number] | null>(null)

  return (
    <div className="flex h-full flex-col bg-[#06080c] p-8">
      <div className="mb-6 flex items-center justify-between border-b border-white/5 pb-6">
        <div className="flex items-center gap-3">
          <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3">
            <RiImage2Line className="text-emerald-400" size={24} />
          </div>
          <div>
            <h2 className="text-sm font-bold tracking-[0.22em] text-zinc-100">VISUAL VAULT</h2>
            <p className="mt-1 text-[10px] font-mono tracking-[0.18em] text-zinc-500">GENERATED BY JARVIS</p>
          </div>
        </div>
        <div className="rounded-lg border border-emerald-500/20 bg-emerald-500/10 px-4 py-2 text-[10px] font-mono tracking-[0.18em] text-emerald-300">
          {images.length} ARTIFACTS
        </div>
      </div>

      {images.length === 0 ? (
        <div className="flex flex-1 flex-col items-center justify-center gap-4 text-zinc-700">
          <RiGalleryLine size={42} className="opacity-25" />
          <span className="text-[10px] font-mono tracking-[0.28em]">NO ARTIFACTS FOUND</span>
        </div>
      ) : (
        <div className="scrollbar-small grid flex-1 grid-cols-2 gap-5 overflow-y-auto pr-2 md:grid-cols-3 xl:grid-cols-5">
          {images.map((img) => (
            <button
              key={img.filename}
              onClick={() => setSelected(img)}
              className="group relative aspect-[16/10] overflow-hidden rounded-2xl border border-white/5 bg-zinc-900/60 transition-all hover:border-emerald-500/40 hover:shadow-[0_0_30px_rgba(16,185,129,0.12)]"
            >
              <img src={img.url} alt={img.displayName} className="h-full w-full object-cover opacity-75 transition-all duration-500 group-hover:scale-105 group-hover:opacity-100" />
              <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black via-black/60 to-transparent p-4 text-left">
                <div className="line-clamp-1 text-[11px] font-bold uppercase tracking-[0.12em] text-zinc-100">{img.displayName}</div>
                <div className="mt-1 text-[9px] font-mono tracking-[0.18em] text-emerald-400/80">{img.source}</div>
              </div>
            </button>
          ))}
        </div>
      )}

      <AnimatePresence>
        {selected ? (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-8">
            <div className="relative flex max-h-full w-full max-w-6xl flex-col items-center gap-6">
              <button onClick={() => setSelected(null)} className="absolute right-0 top-0 rounded-full border border-white/10 bg-white/5 p-3 text-zinc-400 transition-colors hover:border-red-500/30 hover:bg-red-500/10 hover:text-red-400">×</button>
              <img src={selected.url} alt={selected.displayName} className="max-h-[74vh] max-w-full rounded-2xl border border-white/10 object-contain shadow-[0_0_80px_rgba(0,0,0,0.8)]" />
              <div className="flex items-center gap-4 rounded-2xl border border-white/5 bg-black/60 px-6 py-4 backdrop-blur-md">
                <div>
                  <div className="text-lg font-bold text-white">{selected.displayName}</div>
                  <div className="text-[10px] font-mono tracking-[0.18em] text-zinc-500">{new Date(selected.createdAt).toLocaleString()}</div>
                </div>
                <button onClick={() => window.desktopApi?.openPath?.(selected.path)} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-[11px] font-bold tracking-[0.16em] text-zinc-200 transition-colors hover:border-emerald-500/30 hover:bg-emerald-500/10 hover:text-emerald-200">
                  <RiFolderOpenLine /> OPEN FOLDER
                </button>
              </div>
            </div>
          </motion.div>
        ) : null}
      </AnimatePresence>
    </div>
  )
}
