"""
J.A.R.V.I.S — WebAutomationPlugin
Browser automation for login and form interaction.

Auto-generated by JARVIS Self-Modification Engine. Fixed to follow PluginBase contract.
"""

import os
import time

from core.plugin_manager import PluginBase


class WebAutomationPlugin(PluginBase):
    """
    Automated web browser control using Selenium.

    Commands:
        /browser: Start Chrome browser
        /goto: Navigate to a URL
        /unilogin: Login to university portal (prompts for credentials)
        /click: Click an element on the page
    """

    name = "web_automation"
    description = "Browser automation for login and web tasks"

    def activate(self):
        self.driver = None
        print("[web_automation] Plugin activated")

    def deactivate(self):
        self._cleanup()

    def on_command(self, command: str, args: str) -> bool:
        if command == "/browser":
            result = self._start_browser()
            self.jarvis.chat.add_message("assistant", result)
            return True
        if command == "/goto":
            if not args.strip():
                self.jarvis.chat.add_message("assistant", "Provide a URL. Usage: /goto https://...")
                return True
            result = self._navigate(args.strip())
            self.jarvis.chat.add_message("assistant", result)
            return True
        if command == "/unilogin":
            result = self._uni_login(args)
            self.jarvis.chat.add_message("assistant", result)
            return True
        if command == "/click":
            if not args.strip():
                self.jarvis.chat.add_message("assistant", "Provide a CSS selector. Usage: /click #submit")
                return True
            result = self._click(args.strip())
            self.jarvis.chat.add_message("assistant", result)
            return True
        return False

    # ── Browser control ───────────────────────────────────────

    def _start_browser(self) -> str:
        try:
            from selenium import webdriver
            from selenium.webdriver.chrome.options import Options

            opts = Options()
            opts.add_argument("--disable-blink-features=AutomationControlled")
            opts.add_experimental_option("excludeSwitches", ["enable-automation"])
            opts.add_experimental_option("useAutomationExtension", False)

            self.driver = webdriver.Chrome(options=opts)
            self.driver.execute_script(
                "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
            )
            return "Browser started."
        except Exception as e:
            return f"Failed to start browser: {e}"

    def _navigate(self, url: str) -> str:
        if not self.driver:
            start = self._start_browser()
            if "Failed" in start:
                return start
        try:
            self.driver.get(url)
            return f"Navigated to {url}"
        except Exception as e:
            return f"Navigation failed: {e}"

    def _click(self, selector: str) -> str:
        if not self.driver:
            return "No browser session active. Use /browser first."
        try:
            from selenium.webdriver.common.by import By
            from selenium.webdriver.support.ui import WebDriverWait
            from selenium.webdriver.support import expected_conditions as EC

            el = WebDriverWait(self.driver, 10).until(
                EC.element_to_be_clickable((By.CSS_SELECTOR, selector))
            )
            el.click()
            return f"Clicked: {selector}"
        except Exception as e:
            return f"Click failed: {e}"

    def _uni_login(self, args: str) -> str:
        """Login to University of Hertfordshire.

        Credentials should be set as environment variables:
            JARVIS_UNI_USER and JARVIS_UNI_PASS
        Or passed as: /unilogin user@herts.ac.uk password
        """
        # Parse credentials
        parts = args.strip().split(None, 1) if args.strip() else []
        if len(parts) == 2:
            username, password = parts
        else:
            username = os.environ.get("JARVIS_UNI_USER", "")
            password = os.environ.get("JARVIS_UNI_PASS", "")

        if not username or not password:
            return (
                "Credentials not provided.\n"
                "Set env vars JARVIS_UNI_USER and JARVIS_UNI_PASS,\n"
                "or use: /unilogin your@email.com yourpassword"
            )

        if not self.driver:
            start = self._start_browser()
            if "Failed" in start:
                return start

        try:
            from selenium.webdriver.common.by import By
            from selenium.webdriver.support.ui import WebDriverWait
            from selenium.webdriver.support import expected_conditions as EC

            self.driver.get("https://studynet.herts.ac.uk/")
            wait = WebDriverWait(self.driver, 15)

            # Try multiple selectors for username field
            for sel in ["#username", "#user", "[name='username']",
                        "[name='loginfmt']", "[type='email']"]:
                try:
                    field = wait.until(EC.presence_of_element_located(
                        (By.CSS_SELECTOR, sel)))
                    field.clear()
                    field.send_keys(username)
                    break
                except Exception:
                    continue
            else:
                return "Could not find username field on login page."

            time.sleep(1)

            # Password field
            for sel in ["#password", "#passwd", "[name='password']",
                        "[name='passwd']", "[type='password']"]:
                try:
                    field = self.driver.find_element(By.CSS_SELECTOR, sel)
                    field.clear()
                    field.send_keys(password)
                    break
                except Exception:
                    continue
            else:
                return "Could not find password field."

            time.sleep(1)

            # Submit
            for sel in ["[type='submit']", "#login", "#submit",
                        "button[type='submit']"]:
                try:
                    btn = self.driver.find_element(By.CSS_SELECTOR, sel)
                    btn.click()
                    break
                except Exception:
                    continue
            else:
                return "Could not find login button."

            time.sleep(5)
            url = self.driver.current_url
            if "login" in url.lower() or "error" in url.lower():
                return f"Login may have failed. Page: {url}"
            return f"Login successful. Page: {url}"

        except Exception as e:
            return f"Login error: {e}"

    def _cleanup(self):
        if self.driver:
            try:
                self.driver.quit()
            except Exception:
                pass
            self.driver = None
